drop table if exists author cascade;
drop table if exists book_author cascade;
drop table if exists books cascade;
drop table if exists publishers cascade;
drop table if exists reviews cascade;


CREATE TABLE if not exists author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE if not exists book_author
(
    author_id BIGINT NOT NULL,
    book_id   BIGINT NOT NULL
);

CREATE TABLE if not exists books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    isbn         VARCHAR(255)                            NOT NULL,
    publisher_id BIGINT,
    price        DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE if not exists publishers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_publishers PRIMARY KEY (id)
);

CREATE TABLE if not exists reviews
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content VARCHAR(255)                            NOT NULL,
    rating  INT                                     NOT NULL,
    book_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);
alter table if exists book_author
    add constraint FKbjqhp85wjv8vpr0beygh6jsgo
        foreign key (author_id)
            references author;
alter table if exists book_author
    add constraint FK91ierknt446aaqnjl4uxjyls3
        foreign key (book_id)
            references books;
alter table if exists books
    add constraint FKayy5edfrqnegqj3882nce6qo8
        foreign key (publisher_id)
            references publishers;
alter table if exists reviews
    add constraint FK6a9k6xvev80se5rreqvuqr7f9
        foreign key (book_id)
            references books;

